### ISSUE TITLE
[FEAT] 위치 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by ehgus0526** [Room-In-Us/Room-In-Us-Front#17]
### 🚀 Description
위치 페이지 레이아웃 구현

### ✅ To-Do
- [x] 위치 페이지 첫 화면 레이아웃
- [x] 지역별 선택 화면 레이아웃
- [x] 지역 이름 선택 화면 레이아웃
- [x] 지역 이름별 상세 화면 레이아웃
- [x] 방탈출 이름별 상세 화면 레이아웃
