### ISSUE TITLE
[FEAT] 게시판 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by hdg0116** [Room-In-Us/Room-In-Us-Front#22]
### 🚀 Description
게시판 페이지 레이아웃 구현

### ✅ To-Do
- [x] 게시판 페이지 레이아웃 구현
- [x] 인생테마 게시판 더보기 페이지 레이아웃 구현
- [x] 게시판 글 쓰기 페이지 레이아웃 구현
