### ISSUE TITLE
[FEAT] 숙련도 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by hdg0116** [Room-In-Us/Room-In-Us-Front#5]
### 🚀 Description
숙련도 페이지 레이아웃 구현

### ✅ To-Do
- [x] 숙련도 페이지 레이아웃 구현
- [x] 카드 전환 효과 기능 구현
- [x] 숙련도 상세 페이지 레이아웃 구현
